// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeLqCs5Ff2lBtkdnUy-Mrw-XvFd0U8KpE',
    appId: '1:218828725526:web:7e5a30b36e1b68fee58437',
    messagingSenderId: '218828725526',
    projectId: 'hon-audit-48a6d',
    authDomain: 'hon-audit-48a6d.firebaseapp.com',
    databaseURL: 'https://hon-audit-48a6d.firebaseio.com',
    storageBucket: 'hon-audit-48a6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBnzXzYWKZgHB7-rCSQRjsUZtAfieGRIM',
    appId: '1:218828725526:android:a039baf450e07252e58437',
    messagingSenderId: '218828725526',
    projectId: 'hon-audit-48a6d',
    databaseURL: 'https://hon-audit-48a6d.firebaseio.com',
    storageBucket: 'hon-audit-48a6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3IdtUlpOlwHVpNhxrvRNrMjljEsIbhlo',
    appId: '1:218828725526:ios:450b5911ed6b7cb2e58437',
    messagingSenderId: '218828725526',
    projectId: 'hon-audit-48a6d',
    databaseURL: 'https://hon-audit-48a6d.firebaseio.com',
    storageBucket: 'hon-audit-48a6d.appspot.com',
    androidClientId: '218828725526-1rb2sisdairednb20k2j79j53ogkfnp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.auditoriaWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3IdtUlpOlwHVpNhxrvRNrMjljEsIbhlo',
    appId: '1:218828725526:ios:6ba6fc321d4837c3e58437',
    messagingSenderId: '218828725526',
    projectId: 'hon-audit-48a6d',
    databaseURL: 'https://hon-audit-48a6d.firebaseio.com',
    storageBucket: 'hon-audit-48a6d.appspot.com',
    androidClientId: '218828725526-1rb2sisdairednb20k2j79j53ogkfnp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.auditoriaWeb.RunnerTests',
  );
}
